name: Provision t3.micro EC2

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-session-token: '${{ secrets.TF_AWS_SESSION_TOKEN }}'
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
          BUCKET_NAME: gopi-ceq-tfstate-bucket
          TF_VAR_STATE_FILE: backup.tfstate
          
        run: |
          cd infra/
          terraform init -no-color -reconfigure -force-copy -backend-config="bucket=$BUCKET_NAME" -backend-config="key=${{ env.TF_VAR_STATE_FILE }}"  -backend-config="encrypt=true"
          terraform validate
          terraform plan 
          terraform apply -auto-approve
          echo "IP=$(terraform output Instance_IP)" >> $GITHUB_OUTPUT
          echo ${{ steps.apply.outputs.IP }} > ../ansible/inventory.txt
          pwd
          ls -larth
          echo "$(cat ../ansible/inventory.txt)"
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Ansible playbook Host:Localhost
        run: |
          ansible --version
          ansible all -i ansible/inventory.txt -m ping
          ansible-playbook ansible/helloworld.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
      - name: Ansible Playbook Host:EC2Instace
        run: |
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa.pem
          chmod 600 /home/runner/.ssh/id_rsa.pem
          echo "changed permission"
          
      - name: Run ansible script
        run: |
          service ssh status
          ansible-playbook -u ec2-user -vvv --private-key /home/runner/.ssh/id_rsa.pem -i ansible/inventory.txt ansible/helloworld.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False    
